"""empty message

Revision ID: 90408787de00
Revises: 6eae48326014
Create Date: 2021-09-26 18:11:25.018407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90408787de00'
down_revision = '6eae48326014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('uq_user_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint('uq_user_number', ['number'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
